blank_issues_enabled: false
# contact_links:
#   - name: Security reports
#     url: https://github.com/chainapsis/oko/security/policy
#     about: Please report vulnerabilities via our security policy.
