services:
  pg_local:
    image: postgres:17.4
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ewallet_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "UTC"
      PGTZ: "UTC"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ewallet_api_server:
    build:
      context: ../../../
      dockerfile: internals/docker/dockerfiles/ewallet_api_server.Dockerfile
    ports:
      - "4200:4200"
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - ../env/ewallet_api_server.env:/home/node/.oko/ewallet_api_server.env:ro
    depends_on:
      - pg_local

volumes:
  pgdata:
