name: Deploy Oko Apps
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Target tag for deployment (format: develop/v0.0.1 or release/v0.0.1)"
        required: true
        type: string
      app:
        description: 'App'
        required: true
        type: choice
        options:
          - 'demo'

jobs:
  publish:
    runs-on: ubuntu-22.04
    container:
      image: node:22.0.0-alpine
    timeout-minutes: 60
    steps:
      - name: Checkout self repository
        uses: actions/checkout@v4

      # - name: Now files are available
      #   run: |
      #     ls -la $GITHUB_WORKSPACE

      # - name: Setup node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "22"
      #     registry-url: "https://registry.npmjs.org"

      - name: Check Node version
        run: node -v

      - name: Enable Corepack
        run: corepack enable

      - name: Yarn version
        run: yarn -v

      - name: Focus root (install only)
        run: yarn workspaces focus @oko-wallet/root

      - name: Install dependencies
        run: yarn install
      #
      # - name: Run the Node.js script
      #   run: tsx ./internals/ci/src/cmds/deploy_2.ts ${{ inputs.tag }}
