name: Deploy Oko Apps
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Target tag for deployment (format: develop/v0.0.1 or release/v0.0.1)"
        required: true
        type: string
      app:
        description: 'App'
        required: true
        type: choice
        options:
          - 'demo'

jobs:
  publish:
    runs-on: ubuntu-22.04
    container:
      image: node:22.0.0-alpine
    timeout-minutes: 60
    environment: develop
    steps:
      - name: Checkout self repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: CHeck Node version
        run: node -v

      - name: Install dependencies
        run: yarn install

      - name: Run the Node.js script
        run: tsx ./internals/ci/src/cmds/deploy_2.ts ${{ inputs.tag }}
